import { AuthProvider } from "@/context/auth/AuthContext";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Lina ERP | Dashboard",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className="h-screen w-full">
        <AuthProvider>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
